---

- hosts: common
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - certs 
  tags:
    - certs 
 
- hosts: master
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - master
  tags:
    - master

- hosts: minion
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - minion 
  tags:
    - minion

- hosts: etcd
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: false
  roles:
    - etcd
  tags:
    - etcd

- hosts: apiserver
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: false
  roles:
    - apiserver
  tags:
    - apiserver

- hosts: flannel
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: false
  roles:
    - flannel
  tags:
    - flannel
