---
- hosts: etcd
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - etcd
  tags:
    - etcd

- hosts: common
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - certs 
  tags:
    - certs 
