---
- hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - common
  tags:
    - common

- hosts: centos
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - centos
  tags:
    - centos

- hosts: raspbian
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - raspbian
  tags:
    - raspbian

- hosts: nfs_servers
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - nfs_servers
  tags:
    - nfs_servers

- hosts: nfs_clients
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - nfs_clients
  tags:
    - nfs_clients

- hosts: docker
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - docker
  tags: 
    - docker

- hosts: volume_groups
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true
  roles:
    - volume_groups
  tags:
    - fs
