---

- hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free

  tasks:
    - include: roles/create_users/main.yml
    - include: roles/create_groups/main.yml
  #oles:
    #- create_groups
    #- create_users

