---

- hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true

#  tasks:
#    - include: roles/create_users/main.yml
#    - include: roles/create_groups/main.yml

- hosts: centos
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - centos

- hosts: raspbian
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - raspbian
