---

- hosts: all
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  gather_facts: true

  roles:
    - common

- hosts: centos
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - centos

- hosts: raspbian
  remote_user: deploy
  become: yes
  become_method: sudo
  strategy: free
  roles:
    - raspbian
