---

- name: stop etcd
  service: name=etcd state=stopped

- name: create /etc/etcd directory
  file:
    path=/etc/etcd
    state=directory
    owner=root
    group=root

- name: copy etcd binary
  copy:
    src=files/etcd
    dest=/usr/bin/etcd
    owner=root
    group=root
    mode=775

- name: copy etcdctl binary
  copy:
    src=files/etcdctl
    dest=/usr/bin/etcdctl
    owner=root
    group=root
    mode=775

- name: copy systemd service file
  template: 
    src=templates/etcd.service.j2
    dest=/etc/systemd/system/etcd.service
    owner=root
    group=root
    mode=644

- name: reload systemd
  command: systemctl daemon-reload

- name: start etcd
  service: name=etcd enabled=true state=restarted


