---
- name: Create volume group
  lvg: vg=vg.{{ansible_hostname}} pvs=/dev/sda
  tags:
    - fs 
  when: ansible_architecture == "armv7l"

- name: Create logical volume for /var
  lvol: vg=vg.{{ansible_hostname}} lv=var size=100%FREE
  tags:
    - fs 
  when: ansible_architecture == "armv7l"


- name: Create ext4 filesystem for /var
  filesystem: fstype=ext4 dev=/dev/mapper/vg.{{ansible_hostname}}-var
  tags:
    - fs 
  when: ansible_architecture == "armv7l"

  ## need to move old /var to new volume group now.

- name: reload systemd
  command:  systemctl daemon-reload

- name: restart docker
  service: name=docker state=restarted
  tags:
    - fs
