---
- name: Create volume group
  lvg: vg=vg.{{ansible_hostname}} pvs=/dev/sda
  tags:
    - fs 
  when: ansible_architecture == "armv7l"

- name: Create logical volume /var/lib/machinename/docker 
  lvol: vg=vg.{{ansible_hostname}} lv=var-lib-{{ansible_hostname}}-docker size=10G
  tags:
    - fs 
  when: ansible_architecture == "armv7l"


- name: Create ext4 filesystem for vg.machinename-var-lib-machinename-docker.  Note logical volume names with hyphens get double-hyphenated.
  filesystem: fstype=ext4 dev=/dev/mapper/vg.{{ansible_hostname}}-var--lib--{{ansible_hostname}}--docker
  tags:
    - fs 
  when: ansible_architecture == "armv7l"


- name: Mount it on /var/lib/{{ansible_hostname}}/docker
  mount: name=/var/lib/{{ansible_hostname}}/docker src=/dev/mapper/vg.{{ansible_hostname}}-var--lib--{{ansible_hostname}}--docker opts=rw state=mounted fstype=ext4
  tags:
    - fs 
  when: ansible_architecture == "armv7l"

- name: reload systemd
  command:  systemctl daemon-reload

- name: restart docker
  service: name=docker state=restarted
  tags:
    - fs
