---
- name: add dev users
  user: name={{item.name}} password={{item.password}} state=present groups=dev,docker generate_ssh_key=yes shell=/bin/bash state=present
  with_items: "{{dev_users}}"

- name: create user deploy
  user:  name={{item.name}} password={{item.password}} group=deploy generate_ssh_key=yes createhome=no shell=/bin/bash state=present
  with_items: "{{deploy_user}}"

- name: copy .profile to home
  copy: src={{files_path}}/profile dest={{item.home}}/.profile owner={{item.name}} group=dev mode=644
  with_items: "{{dev_users}}"

- name: copy .bashrc to home
  copy: src={{files_path}}/bashrc dest={{item.home}}/.bashrc owner={{item.name}} group=dev mode=644
  with_items: "{{dev_users}}"

- name: copy .bash_prompt to home
  copy: src={{files_path}}/bash_prompt dest={{item.home}}/.bash_prompt owner={{item.name}} group=dev mode=644
  with_items: "{{dev_users}}"
