---
- name: determine os
  raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro
  always_run: yes

- name: install docker
  when:  "'CentOS' in distro.stdout"
  package: name=docker.io state=latest

- name: install hypriot docker
  when:  "'Raspbian' in distro.stdout"
  package: name=docker-hypriot state=latest

- name: create docker drop in directory
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: add docker --graph drop in file
  when:  "'Raspbian' in distro.stdout"
  template: src=docker.service.conf.j2 dest=/etc/systemd/system/docker.service.d/docker.service.conf
