---

- name: Install socat
  apt: name=socat state=present

        
- name: kubelet
  copy:
    src=files/kubelet
    dest=/usr/bin/kubelet
    owner=root
    group=root
    mode=755


- name: kube-proxy
  copy:
    src=files/kube-proxy
    dest=/usr/bin/kube-proxy
    owner=root
    group=root
    mode=755

- name: kubectl
  copy:
    src=files/kubectl
    dest=/usr/bin/kubectl
    owner=root
    group=root
    mode=755

- name: minion kubeconfig
  copy:
    src=files/{{ansible_hostname}}.kubeconfig
    dest=/home/tom/{{ansible_hostname}}.kubeconfig
    owner=tom
    group=dev
    mode=644

- name: kube-proxy kubeconfig
  copy:
    src=files/kube-proxy.kubeconfig
    dest=/home/tom/kube-proxy.kubeconfig
    owner=tom
    group=dev
    mode=644 
